# Generated by Django 3.1.14 on 2023-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0005_alter_blacklistip_id_alter_blacklistuseragent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blacklistuseragent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='object_pk',
            field=models.SlugField(max_length=255, verbose_name='object ID'),
        ),
    ]
